name: Push Code to Another Repo

on:
  push:
    branches:
      - master

jobs:
  push-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      
    - name: Transfer Code
      uses: VenkySubbaraj/Data_pipeline@master
      env:
        DESTINATION_REPO_TOKEN: ${{ secrets.DESTINATION_REPO_TOKEN }}
      with:
          source-files: 'Data_pipeline/'
          destination-username: 'venkatsubbaraj'
          destination-repository: 'clone'
          commit-email: 'venkatachalapathysubbaraj@outlook.com'
