name: Copy Folder

on:
  push:
    branches:
      - master

jobs:
  copy_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Copy folder
        run: |
          mkdir copied_folder
          cd ../../../../../
          pwd
          ls

      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: venkatsubbaraj/clone
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git clone https://github.com/VenkySubbaraj/Data_Pipeline.git copy_folder
          cd ../../../../../
          pwd
          ls
          git config --global user.name "venkatsubbaraj"
          git config --global user.email "venkatachalapathysubbaraj@outlook.com"
          git add .
          git commit -m "Copy folder"
          git push origin main
