name: Copy Folder

on:
  push:
    branches:
      - master

jobs:
  copy_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Copy folder
        run: |
          git clone https://github.com/VenkySubbaraj/Data_Pipeline.git copied_folder
          cd copied_folder
          ls

      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: venkatsubbaraj/clone
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./copied_folder

      - name: Commit and push changes
        run: |
          git remote remove origin https://github.com/VenkySubbaraj/Data_Pipeline.git
          git remote add origin https://github.com/venkatsubbaraj/clone.git
          git config --global user.name "venkatsubbaraj"
          git config --global user.email "venkatachalapathysubbaraj@outlook.com"
          git add .
          git commit -m "Copy folder"
          git push origin master
