name: Sync Code

on:
  push:
    branches:
      - master  # Change this to your desired branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: VenkySubbaraj/Data_Pipeline

      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: venkatsubbaraj/clone
          token: ${{ secrets.DESTINATION_REPO_TOKEN }}
      
      - name: remove code from repository
        run: |
          rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}
          cd ${{ github.workspace }}
          pwd
          #git clone --depth 1 https://github.com/venkatsubbaraj/clone.git ${{ github.workspace }}
          
      - name: Sync code
        run: |
          rsync -Rr ${{ github.workspace }}/. ${{ github.workspace }}/destination/
          cd ${{ github.workspace }}/destination
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Transfer code from source repository"
          git push
