# name: Copy Code to Another Repo

# on:
#   push:
#     branches:
#       - master

# jobs:
#   copy_code:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source repository
#         uses: actions/checkout@v2

#       - name: Checkout target repository
#         uses: actions/checkout@v2
#         with:
#           repository: venkatsubbaraj/clone  # Replace with the target repository owner and name

#       - name: Copy code
#         run: |
#           rsync -av --ignore-existing ./* ./  # Replace with the appropriate source and target paths

#       - name: Commit and push changes
#         run: |
#           git config --local user.email "venkats1909@gmail.com"
#           git config --local user.name "venkat"
#           git status
#           git add .
#           git commit -m "Automatically copied code from source repository"
#           git push


name: Push Code to Another Repo

on:
  push:
    branches:
      - master

jobs:
  push-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: venkatsubbaraj/clone
        token: ${{ secrets.SOURCE_REPO_TOKEN }}
        ref: master
        
    - name: Copy directories
      run: |
        rsync -av --ignore-existing ./* ./

    - name: Push code to destination repository
      run: |
        git init
        pwd
        git config --local user.email "venkats1909@gmail.com"
        git config --local user.name "venkatsubbaraj"
        git remote rm origin
        git remote add origin https://github.com/venkatsubbaraj/clone.git
        git push -f origin master
