name: Copy Code to Another Repo

on:
  push:
    branches:
      - master

jobs:
  copy_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: venkatsubbaraj/clone  # Replace with the target repository owner and name

      - name: Copy code
        run: |
          cp -r ./* clone/  # Replace with the appropriate source and target paths

      - name: Commit and push changes
        run: |
          cd ./
          git config --local user.email "venkats1909@gmail.com"
          git config --local user.name "venkat"
          git add .
          git commit -m "Automatically copied code from source repository"
          git push
