name: Copy Latest File

on:
  push:
    branches:
      - master

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Copy file from source repository
      run: |
        rsync -av --ignore-existing . ./

    - name: Checkout destination repository
      uses: actions/checkout@v2
      with:
        repository: venkatsubbaraj/clone
        token: ${{ secrets.DESTINATION_REPO_TOKEN }}
        ref: master
   
    - name: git setup
      run: |
        git config --local user.email "venkatachalapathysubbaraj@outlook.com"
        git config --local user.name "venkatsubbaraj"
        
    - name: Fetch latest changes from source repository
      run: |
        git remote add source https://github.com/VenkySubbaraj/Data_Pipeline.git
        git fetch source
        
    - name: Copy file to destination repository
      run: |
        git remote rm origin
        git remote add origin https://github.com/venkatsubbaraj/clone.git
        git fetch origin
        git pull origin master
        git push -f origin update:latest_commit 
        
