name: Copy Latest File

on:
  push:
    branches:
      - master

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Copy file from source repository
      run: |
        rsync -av --ignore-existing . ./

    - name: Checkout destination repository
      uses: actions/checkout@v2
      with:
        repository: venkatsubbaraj/clone
        token: ${{ secrets.DESTINATION_REPO_TOKEN }}
        ref: master

    - name: Copy file to destination repository
      run: |
        git config --local user.email "venkatachalapathysubbaraj@outlook.com"
        git config --local user.name "venkatsubbaraj"
        git add .
        git commit -m "Copy latest file"
        git push -f https://venkatsubbaraj:${{secrets.DESTINATION_REPO_TOKEN}}/venkatsubbaraj/clone.git HEAD:venkata_code_updation
