# name: Copy Latest File

# on:
#   push:
#     branches:
#       - master

# jobs:
#   copy-file:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Copy file from source repository
#       run: |
#         rsync -av --ignore-existing . ./

#     - name: Checkout destination repository
#       uses: actions/checkout@v2
#       with:
#         repository: venkatsubbaraj/clone
#         token: ${{ secrets.DESTINATION_REPO_TOKEN }}
#         ref: master
   
#     - name: git setup
#       run: |
#         git config --local user.email "venkatachalapathysubbaraj@outlook.com"
#         git config --local user.name "venkatsubbaraj"
        
#     - name: Fetch latest changes from source repository
#       run: |
#         git remote add source https://github.com/VenkySubbaraj/Data_Pipeline.git
#         git fetch source
        
#     - name: Copy file to destination repository
#       run: |
#         git diff master origin/venkata_code_updation
#         git fetch origin
#         #git pull origin master
#         #git push -f origin update:latest_commit 
        



# name: Sync Code

# on:
#   push:
#     branches:
#       - master  # Change this to your desired branch

# jobs:
#   sync:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source repository
#         uses: actions/checkout@v2
#         with:
#           repository: VenkySubbaraj/Data_Pipeline

#       - name: Checkout destination repository
#         uses: actions/checkout@v2
#         with:
#           repository: venkatsubbaraj/clone
#           token: ${{ secrets.DESTINATION_REPO_TOKEN }}

#       - name: Sync code
#         run: |
#           git clone --depth 1 https://github.com/venkatsubbaraj/clone.git destination
#           cp -R ${{ github.workspace }}/* destination/
          
#           pwd
#           ls
#           git add .
#           git config user.name "venkatsubbaraj"
#           git config user.email "venkatachalapathysubbaraj@outlook.com"
#           git commit -m "Sync code from source repository"
#           git push


name: Transfer Code

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source Repository'
        required: true
      destination_repo:
        description: 'Destination Repository'
        required: true
      branch:
        description: 'Branch'
        required: true

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.source_repo }}
          ref: ${{ github.event.inputs.branch }}

      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.destination_repo }}
          token: ${{ secrets.DESTINATION_REPO_TOKEN }}
          ref: ${{ github.event.inputs.branch }}

      - name: Copy code to destination repository
        run: |
          rsync -Rr ../../../..${{ github.workspace }}/ ${{ github.workspace }}/destination/
          cd ${{ github.workspace }}/destination
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Transfer code from source repository"
          git push




