name: Push Code to Another Repo

on:
  push:
    branches:
      - master

jobs:
  push-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      
    - name: Transfer Code
      uses: VenkySubbaraj/Data_pipeline@master
      env:
        DESTINATION_REPO_TOKEN: ${{ secrets.DESTINATION_REPO_TOKEN }}
      with:
        source_file: 'README.md'
        destination_repo: 'VenkatSubbaraj/clone'
        user_email: 'venkats1909@gmail.com'
        user_name: 'VenkatSubbaraj'
        commit_message: 'commit-message'
